---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: networking-2
spec:
  syncMode: ContinuousWithDriftDetection
  helmCharts:
  - repositoryURL:    https://helm.cilium.io/
    repositoryName:   cilium
    chartName:        cilium/cilium
    chartVersion:     1.16.3
    releaseName:      kube-system-cilium
    releaseNamespace: kube-system
    helmChartAction:  Install
---
apiVersion: config.projectsveltos.io/v1beta1
kind: ClusterProfile
metadata:
  name: external-dns
spec:
  syncMode: ContinuousWithDriftDetection
  helmCharts:
  - repositoryURL:    https://kubernetes-sigs.github.io/external-dns
    repositoryName:   external-dns
    chartName:        external-dns/external-dns
    chartVersion:     1.15.0
    releaseName:      external-dns
    releaseNamespace: buttah-system
    helmChartAction:  Install
    